FROM python:3.10.10

WORKDIR /app

COPY www ./www

COPY .streamlit ./.streamlit

COPY requirements-front.txt requirements.txt

RUN pip3 install -r requirements.txt

CMD ["streamlit", "run", "www/index.py"]