version: '3.6'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 5000:5000
    volumes:
      - ./database.sqlite:/app/database.sqlite

  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - 8080:8080
    environment:
      - API_URL=http://api:5000
  